### ISSUE TITLE
pbkit license (AFL) is not compatible with GPL

### ISSUE THREAD

**Issue by JayFoxRox** [xqemu/nxdk#21]
This was recently brought to my attention - I was not aware.

This is indeed an issue we should solve (Although I honestly don't care too much as the authors probably wouldn't care). We should still reach out and try to figure something out.

openxdkman is the original author and also goes by the name ps2devman in the PS2 scene.
They also worked on xenkit for the 360.

Unfortunately, xbox-scene and ps2dev are offline, so we can't reach them there anymore.

---

@maturion @caustik-divx / @caustik / @tmbinc any idea how to reach openxdkman?

I've also asked elsewhere, this reddit lists some things I've tried: https://www.reddit.com/r/originalxbox/comments/6mnr67/looking_for_openxdkman_author_of_pbkit/ and ps2dev IRC already.

**Comment by espes** [comment]
Fixed in 2b88226f133b68418e901e6394de2a7c49d93bc8

**Comment by mborgerson** [comment]
Well, that was easy. Safe to assume we got re-license permission from original author?

**Comment by espes** [comment]
yup

**Comment by JayFoxRox** [comment]
Can you add the actual response or at least give more info?
- Are we allowed to use it under that license? Are we the new license holder? ..

While this fixes the OpenXDK incompatibility, it's probably still not legal to release binary builds without source (or non-GPL code in general) when using pbkit.

**Comment by mborgerson** [comment]
By the way, some of the networking code is also under AFL. Can we get re-license for that too?

https://github.com/xqemu/nxdk/tree/master/lib/net/pktdrv

**Comment by espes** [comment]
openxdkman ofc still owns the copyright but has given permission to distribute under LGPL, like any open source software. a license holder isn't a thing.

as LGPL, binaries can be distributed without source with unmodified pbKit. But nxdk builds are stuck as GPL as long as we use chunks of the linux kernel as the USB stack.

**Comment by thrimbor** [comment]
> as LGPL, binaries can be distributed without source with unmodified pbKit.

It's a bit more complicated, unfortunately.

Section 4.d of the LGPL states that, to combine your proprietary work (i.e. your Xbox-program) with LGPL-licensed work (i.e. pbkit) you need to do one of the following things:

1. Make the LGPL-licensed work a shared library and dynamically link it with your proprietary code (impossible on Xbox), or
2. provide object-files of your proprietary code such that your proprietary parts can be relinked with the LGPL-licensed parts.

To create a legal binary containing closed-source and (L)GPL-parts a linking-exception is needed (sometimes called a Classpath-exception, I think). [It's the way libgcc does this, too](https://www.gnu.org/licenses/gcc-exception-3.1-faq.en.html).

> But nxdk builds are stuck as GPL as long as we use chunks of the linux kernel as the USB stack.

A new USB-stack is on my ToDo-list (I have a USB-controller book lying around, which I bought for OS-dev purposes), but there are more important things for me to do right now (back when I came up with the idea it was only because I wanted to use Xbox360 wireless controllers on my Xbox) :grimacing:

Anyway, relicensing the AFL-parts is a good step already.

**Comment by LukeUsher** [comment]
Dynamic linking is not completely impossible, I'm sure it would be possible to add a runtime linker to nxdk that can be called before main. That said, L/GPL is perhaps not the best license for this stuff. A little late to change that now ;)

**Comment by thrimbor** [comment]
> Dynamic linking is not completely impossible, I'm sure it would be possible to add a runtime linker to nxdk that can be called before main.

Well, not impossible, but the platform doesn't provide a clean way to do it. Sure, you could have some kind of "nxdk-binary" that loads the actual program and links it, but it would be pretty complicated and messy. And since your code would need to be kept in a separate executable, you could just go for the "provide object-files" method anyway.

> That said, L/GPL is perhaps not the best license for this stuff.

Unfortunately, a lot of other licenses allow for the free code to become unfree (by allowing integration into proprietary software without having to disclose the, eventually modified, code - it's what Apple does with clang, and Sony with FreeBSD...), which I guess is something the original authors of OpenXDK did not want. LGPL doesn't provide a real benefit over GPL here because we're not dealing with dynamically linked libraries. I really think GPL + linking exception is a good license for a project like this, because it ensures that all the free code (and modified variants of it) stay free while still allowing to combine it with proprietary work into one single executable.

For me, personally, GPL is fine. But it may be one hindering factor in more widespread adoption of the project.

> A little late to change that now ;)

There are quite a few projects which re-licensed an already huge codebase - I think even VLC managed to pull it off. It's just a lot of work to find all the original authors and get their agreement ;)

**Comment by espes** [comment]
I can get permission for pbKit to be made public domain, the author really doesn't care. Most of nxdk *doesn't even have a license* at the moment.

The hindering factor preventing widespread adoption of this project is that it's not very good. Let's see some PR's instead of more fussing, shall we?
